/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.socketchat.ui;

/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        elGamalContentPanel = new javax.swing.JPanel();
        elGamalFieldsPanel = new javax.swing.JPanel();
        elGamalGLabel = new javax.swing.JLabel();
        elGamalGField = new javax.swing.JTextField();
        elGamalPLabel = new javax.swing.JLabel();
        elGamalPField = new javax.swing.JTextField();
        elGamalXLabel = new javax.swing.JLabel();
        elGamalXField = new javax.swing.JTextField();
        elGamalKLabel = new javax.swing.JLabel();
        elGamalKField = new javax.swing.JTextField();
        elGamalYLabel = new javax.swing.JLabel();
        elGamalYField = new javax.swing.JTextField();
        elGamalEphemeralLabel = new javax.swing.JLabel();
        elGamalEphemeralField = new javax.swing.JTextField();
        elGamalActionsPanel = new javax.swing.JPanel();
        elGamalRandomButton = new javax.swing.JButton();
        elGamalCalculateButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        controlsPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        startCheck = new javax.swing.JCheckBox();
        spacerLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        encryptionCheck = new javax.swing.JCheckBox();
        hexKeyLabel = new javax.swing.JLabel();
        hexKeyField = new javax.swing.JTextField();
        elGamalCheck = new javax.swing.JCheckBox();
        viewElGamalButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        addressHeaderPanel = new javax.swing.JPanel();
        addressesLabel = new javax.swing.JLabel();
        addAddressLabel = new javax.swing.JLabel();
        addressScrollPane = new javax.swing.JScrollPane();
        addressList = new javax.swing.JList();
        messagePanel = new javax.swing.JPanel();
        messageHeaderPanel = new javax.swing.JPanel();
        messagesLabel = new javax.swing.JLabel();
        clearLabel = new javax.swing.JLabel();
        messageScrollPane = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        messageInputPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        elGamalContentPanel.setLayout(new java.awt.BorderLayout(0, 10));

        elGamalFieldsPanel.setLayout(new java.awt.GridLayout(0, 2, 8, 8));

        elGamalGLabel.setText("G");
        elGamalFieldsPanel.add(elGamalGLabel);
        elGamalFieldsPanel.add(elGamalGField);

        elGamalPLabel.setText("P");
        elGamalFieldsPanel.add(elGamalPLabel);
        elGamalFieldsPanel.add(elGamalPField);

        elGamalXLabel.setText("x (private identity)");
        elGamalFieldsPanel.add(elGamalXLabel);
        elGamalFieldsPanel.add(elGamalXField);

        elGamalKLabel.setText("k (private ephemeral)");
        elGamalFieldsPanel.add(elGamalKLabel);
        elGamalFieldsPanel.add(elGamalKField);

        elGamalYLabel.setText("y = G^x mod P");
        elGamalFieldsPanel.add(elGamalYLabel);

        elGamalYField.setEditable(false);
        elGamalFieldsPanel.add(elGamalYField);

        elGamalEphemeralLabel.setText("ephemeral = G^k mod P");
        elGamalFieldsPanel.add(elGamalEphemeralLabel);

        elGamalEphemeralField.setEditable(false);
        elGamalFieldsPanel.add(elGamalEphemeralField);

        elGamalContentPanel.add(elGamalFieldsPanel, java.awt.BorderLayout.CENTER);

        elGamalActionsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 0));

        elGamalRandomButton.setText("Random x and k");
        elGamalActionsPanel.add(elGamalRandomButton);

        elGamalCalculateButton.setText("Calculate");
        elGamalActionsPanel.add(elGamalCalculateButton);

        elGamalContentPanel.add(elGamalActionsPanel, java.awt.BorderLayout.SOUTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UDP Broadcast Chat");
        setMinimumSize(new java.awt.Dimension(920, 560));

        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setText("(o) UDP BROADCAST");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 14, 7, 14));
        headerPanel.add(titleLabel, java.awt.BorderLayout.NORTH);

        controlsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 14, 10, 14));
        controlsPanel.setLayout(new java.awt.GridBagLayout());

        addressLabel.setText("BROADCAST IP ADDRESS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(addressLabel, gridBagConstraints);

        portLabel.setText("UDP PORT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(portLabel, gridBagConstraints);

        startLabel.setText("START");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(startLabel, gridBagConstraints);

        addressField.setText("255.255.255.255");
        addressField.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(addressField, gridBagConstraints);

        portField.setText("9000");
        portField.setPreferredSize(new java.awt.Dimension(82, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(portField, gridBagConstraints);

        startCheck.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(startCheck, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        controlsPanel.add(spacerLabel, gridBagConstraints);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLabel.setText("* LISTENING");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        controlsPanel.add(statusLabel, gridBagConstraints);

        encryptionCheck.setText("Encryption");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(encryptionCheck, gridBagConstraints);

        hexKeyLabel.setText("HEX KEY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(hexKeyLabel, gridBagConstraints);

        hexKeyField.setEditable(false);
        hexKeyField.setText("00112233445566778899aabbccddeeff");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(hexKeyField, gridBagConstraints);

        elGamalCheck.setText("El Gamal Key Exchange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(elGamalCheck, gridBagConstraints);

        viewElGamalButton.setText("<html><u>View&nbsp;El&nbsp;Gamal</u></html>");
        viewElGamalButton.setBorderPainted(false);
        viewElGamalButton.setContentAreaFilled(false);
        viewElGamalButton.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        controlsPanel.add(viewElGamalButton, gridBagConstraints);

        headerPanel.add(controlsPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        addressPanel.setPreferredSize(new java.awt.Dimension(184, 10));
        addressPanel.setLayout(new java.awt.BorderLayout());

        addressHeaderPanel.setLayout(new java.awt.BorderLayout());

        addressesLabel.setText("ADDRESSES");
        addressesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        addressHeaderPanel.add(addressesLabel, java.awt.BorderLayout.WEST);

        addAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addAddressLabel.setText("+");
        addAddressLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        addressHeaderPanel.add(addAddressLabel, java.awt.BorderLayout.EAST);

        addressPanel.add(addressHeaderPanel, java.awt.BorderLayout.NORTH);

        addressList.setModel(new com.example.socketchat.model.UserModel());
        addressList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        addressList.setFixedCellHeight(26);
        addressScrollPane.setViewportView(addressList);

        addressPanel.add(addressScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(addressPanel, java.awt.BorderLayout.WEST);

        messagePanel.setLayout(new java.awt.BorderLayout());

        messageHeaderPanel.setLayout(new java.awt.BorderLayout());

        messagesLabel.setText("MESSAGES");
        messagesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageHeaderPanel.add(messagesLabel, java.awt.BorderLayout.WEST);

        clearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clearLabel.setText("CLEAR");
        clearLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageHeaderPanel.add(clearLabel, java.awt.BorderLayout.EAST);

        messagePanel.add(messageHeaderPanel, java.awt.BorderLayout.NORTH);

        messages.setEditable(false);
        messages.setColumns(20);
        messages.setLineWrap(true);
        messages.setRows(5);
        messages.setWrapStyleWord(true);
        messages.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        messageScrollPane.setViewportView(messages);

        messagePanel.add(messageScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(messagePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        messageInputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageInputPanel.setLayout(new java.awt.BorderLayout(8, 0));
        messageInputPanel.add(inputField, java.awt.BorderLayout.CENTER);

        sendButton.setText("Send");
        messageInputPanel.add(sendButton, java.awt.BorderLayout.EAST);

        getContentPane().add(messageInputPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAddressLabel;
    public javax.swing.JTextField addressField;
    private javax.swing.JPanel addressHeaderPanel;
    private javax.swing.JLabel addressLabel;
    public javax.swing.JList addressList;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JScrollPane addressScrollPane;
    private javax.swing.JLabel addressesLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel clearLabel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel elGamalActionsPanel;
    public javax.swing.JButton elGamalCalculateButton;
    public javax.swing.JCheckBox elGamalCheck;
    public javax.swing.JPanel elGamalContentPanel;
    public javax.swing.JTextField elGamalEphemeralField;
    private javax.swing.JLabel elGamalEphemeralLabel;
    private javax.swing.JPanel elGamalFieldsPanel;
    public javax.swing.JTextField elGamalGField;
    private javax.swing.JLabel elGamalGLabel;
    public javax.swing.JTextField elGamalKField;
    private javax.swing.JLabel elGamalKLabel;
    public javax.swing.JTextField elGamalPField;
    private javax.swing.JLabel elGamalPLabel;
    public javax.swing.JButton elGamalRandomButton;
    public javax.swing.JTextField elGamalXField;
    private javax.swing.JLabel elGamalXLabel;
    public javax.swing.JTextField elGamalYField;
    private javax.swing.JLabel elGamalYLabel;
    public javax.swing.JCheckBox encryptionCheck;
    private javax.swing.JPanel headerPanel;
    public javax.swing.JTextField hexKeyField;
    public javax.swing.JLabel hexKeyLabel;
    public javax.swing.JTextField inputField;
    private javax.swing.JPanel messageHeaderPanel;
    private javax.swing.JPanel messageInputPanel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JScrollPane messageScrollPane;
    public javax.swing.JTextArea messages;
    private javax.swing.JLabel messagesLabel;
    public javax.swing.JTextField portField;
    private javax.swing.JLabel portLabel;
    public javax.swing.JButton sendButton;
    private javax.swing.JLabel spacerLabel;
    public javax.swing.JCheckBox startCheck;
    private javax.swing.JLabel startLabel;
    public javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JButton viewElGamalButton;
    // End of variables declaration//GEN-END:variables
}
