/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.socketchat.ui;

/**
 *
 * @author User
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        diffieHellmanContentPanel = new javax.swing.JPanel();
        diffieHellmanFieldsPanel = new javax.swing.JPanel();
        diffieHellmanGLabel = new javax.swing.JLabel();
        diffieHellmanGField = new javax.swing.JTextField();
        diffieHellmanPLabel = new javax.swing.JLabel();
        diffieHellmanPField = new javax.swing.JTextField();
        diffieHellmanXLabel = new javax.swing.JLabel();
        diffieHellmanXField = new javax.swing.JTextField();
        diffieHellmanYLabel = new javax.swing.JLabel();
        diffieHellmanYField = new javax.swing.JTextField();
        selectedUserDiffieHellmanYLabel = new javax.swing.JLabel();
        selectedUserDiffieHellmanYField = new javax.swing.JTextField();
        diffieHellmanKLabel = new javax.swing.JLabel();
        diffieHellmanKField = new javax.swing.JTextField();
        diffieHellmanActionsPanel = new javax.swing.JPanel();
        diffieHellmanRandomButton = new javax.swing.JButton();
        diffieHellmanCalculateButton = new javax.swing.JButton();
        diffieHellmanCopyButton = new javax.swing.JButton();
        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        controlsPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        startCheck = new javax.swing.JCheckBox();
        spacerLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        encryptionCheck = new javax.swing.JCheckBox();
        hexKeyLabel = new javax.swing.JLabel();
        hexKeyField = new javax.swing.JTextField();
        diffieHellmanCheck = new javax.swing.JCheckBox();
        viewDiffieHellmanButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        addressHeaderPanel = new javax.swing.JPanel();
        addressesLabel = new javax.swing.JLabel();
        addAddressLabel = new javax.swing.JLabel();
        addressScrollPane = new javax.swing.JScrollPane();
        addressList = new javax.swing.JList();
        messagePanel = new javax.swing.JPanel();
        messageHeaderPanel = new javax.swing.JPanel();
        messagesLabel = new javax.swing.JLabel();
        clearLabel = new javax.swing.JLabel();
        messageScrollPane = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        messageInputPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        diffieHellmanContentPanel.setLayout(new java.awt.BorderLayout(0, 10));

        diffieHellmanFieldsPanel.setLayout(new java.awt.GridLayout(0, 2, 8, 8));

        diffieHellmanGLabel.setText("G");
        diffieHellmanFieldsPanel.add(diffieHellmanGLabel);
        diffieHellmanFieldsPanel.add(diffieHellmanGField);

        diffieHellmanPLabel.setText("P");
        diffieHellmanFieldsPanel.add(diffieHellmanPLabel);
        diffieHellmanFieldsPanel.add(diffieHellmanPField);

        diffieHellmanXLabel.setText("x (private)");
        diffieHellmanFieldsPanel.add(diffieHellmanXLabel);
        diffieHellmanFieldsPanel.add(diffieHellmanXField);

        diffieHellmanYLabel.setText("y = G^x mod P");
        diffieHellmanFieldsPanel.add(diffieHellmanYLabel);

        diffieHellmanYField.setEditable(false);
        diffieHellmanFieldsPanel.add(diffieHellmanYField);

        selectedUserDiffieHellmanYLabel.setText("Selected user's y");
        diffieHellmanFieldsPanel.add(selectedUserDiffieHellmanYLabel);

        diffieHellmanFieldsPanel.add(selectedUserDiffieHellmanYField);

        diffieHellmanKLabel.setText("K (secret key)");
        diffieHellmanFieldsPanel.add(diffieHellmanKLabel);

        diffieHellmanKField.setEditable(false);
        diffieHellmanFieldsPanel.add(diffieHellmanKField);

        diffieHellmanContentPanel.add(diffieHellmanFieldsPanel, java.awt.BorderLayout.CENTER);

        diffieHellmanActionsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 8, 0));

        diffieHellmanRandomButton.setText("Random x");
        diffieHellmanActionsPanel.add(diffieHellmanRandomButton);

        diffieHellmanCalculateButton.setText("Calculate");
        diffieHellmanActionsPanel.add(diffieHellmanCalculateButton);

        diffieHellmanCopyButton.setText("Copy public values");
        diffieHellmanActionsPanel.add(diffieHellmanCopyButton);

        diffieHellmanContentPanel.add(diffieHellmanActionsPanel, java.awt.BorderLayout.SOUTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UDP Broadcast Chat");
        setMinimumSize(new java.awt.Dimension(920, 560));

        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setText("(o) UDP BROADCAST");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 14, 7, 14));
        headerPanel.add(titleLabel, java.awt.BorderLayout.NORTH);

        controlsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 14, 10, 14));
        controlsPanel.setLayout(new java.awt.GridBagLayout());

        addressLabel.setText("BROADCAST IP ADDRESS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(addressLabel, gridBagConstraints);

        portLabel.setText("UDP PORT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(portLabel, gridBagConstraints);

        startLabel.setText("START");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(startLabel, gridBagConstraints);

        addressField.setText("255.255.255.255");
        addressField.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(addressField, gridBagConstraints);

        portField.setText("9000");
        portField.setPreferredSize(new java.awt.Dimension(82, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(portField, gridBagConstraints);

        startCheck.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(startCheck, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        controlsPanel.add(spacerLabel, gridBagConstraints);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLabel.setText("* LISTENING");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        controlsPanel.add(statusLabel, gridBagConstraints);

        encryptionCheck.setText("Encryption");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(encryptionCheck, gridBagConstraints);

        hexKeyLabel.setText("HEX KEY");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(hexKeyLabel, gridBagConstraints);

        hexKeyField.setEditable(false);
        hexKeyField.setText("00112233445566778899aabbccddeeff");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(hexKeyField, gridBagConstraints);

        diffieHellmanCheck.setText("Diffie-Hellman Key Exchange");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(diffieHellmanCheck, gridBagConstraints);

        viewDiffieHellmanButton.setText("<html><u>View&nbsp;Diffie-Hellman</u></html>");
        viewDiffieHellmanButton.setBorderPainted(false);
        viewDiffieHellmanButton.setContentAreaFilled(false);
        viewDiffieHellmanButton.setFocusPainted(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        controlsPanel.add(viewDiffieHellmanButton, gridBagConstraints);

        headerPanel.add(controlsPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        addressPanel.setPreferredSize(new java.awt.Dimension(184, 10));
        addressPanel.setLayout(new java.awt.BorderLayout());

        addressHeaderPanel.setLayout(new java.awt.BorderLayout());

        addressesLabel.setText("ADDRESSES");
        addressesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        addressHeaderPanel.add(addressesLabel, java.awt.BorderLayout.WEST);

        addAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addAddressLabel.setText("+");
        addAddressLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        addressHeaderPanel.add(addAddressLabel, java.awt.BorderLayout.EAST);

        addressPanel.add(addressHeaderPanel, java.awt.BorderLayout.NORTH);

        addressList.setModel(new com.example.socketchat.model.UserModel());
        addressList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        addressList.setFixedCellHeight(26);
        addressScrollPane.setViewportView(addressList);

        addressPanel.add(addressScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(addressPanel, java.awt.BorderLayout.WEST);

        messagePanel.setLayout(new java.awt.BorderLayout());

        messageHeaderPanel.setLayout(new java.awt.BorderLayout());

        messagesLabel.setText("MESSAGES");
        messagesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageHeaderPanel.add(messagesLabel, java.awt.BorderLayout.WEST);

        clearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clearLabel.setText("CLEAR");
        clearLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageHeaderPanel.add(clearLabel, java.awt.BorderLayout.EAST);

        messagePanel.add(messageHeaderPanel, java.awt.BorderLayout.NORTH);

        messages.setEditable(false);
        messages.setColumns(20);
        messages.setLineWrap(true);
        messages.setRows(5);
        messages.setWrapStyleWord(true);
        messages.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        messageScrollPane.setViewportView(messages);

        messagePanel.add(messageScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(messagePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        messageInputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageInputPanel.setLayout(new java.awt.BorderLayout(8, 0));
        messageInputPanel.add(inputField, java.awt.BorderLayout.CENTER);

        sendButton.setText("Send");
        messageInputPanel.add(sendButton, java.awt.BorderLayout.EAST);

        getContentPane().add(messageInputPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAddressLabel;
    public javax.swing.JTextField addressField;
    private javax.swing.JPanel addressHeaderPanel;
    private javax.swing.JLabel addressLabel;
    public javax.swing.JList addressList;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JScrollPane addressScrollPane;
    private javax.swing.JLabel addressesLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel clearLabel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel diffieHellmanActionsPanel;
    public javax.swing.JButton diffieHellmanCalculateButton;
    public javax.swing.JCheckBox diffieHellmanCheck;
    public javax.swing.JPanel diffieHellmanContentPanel;
    public javax.swing.JButton diffieHellmanCopyButton;
    private javax.swing.JPanel diffieHellmanFieldsPanel;
    public javax.swing.JTextField diffieHellmanGField;
    private javax.swing.JLabel diffieHellmanGLabel;
    public javax.swing.JTextField diffieHellmanKField;
    private javax.swing.JLabel diffieHellmanKLabel;
    public javax.swing.JTextField diffieHellmanPField;
    private javax.swing.JLabel diffieHellmanPLabel;
    public javax.swing.JButton diffieHellmanRandomButton;
    public javax.swing.JTextField diffieHellmanXField;
    private javax.swing.JLabel diffieHellmanXLabel;
    public javax.swing.JTextField diffieHellmanYField;
    private javax.swing.JLabel diffieHellmanYLabel;
    public javax.swing.JCheckBox encryptionCheck;
    private javax.swing.JPanel headerPanel;
    public javax.swing.JTextField hexKeyField;
    public javax.swing.JLabel hexKeyLabel;
    public javax.swing.JTextField inputField;
    private javax.swing.JPanel messageHeaderPanel;
    private javax.swing.JPanel messageInputPanel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JScrollPane messageScrollPane;
    public javax.swing.JTextArea messages;
    private javax.swing.JLabel messagesLabel;
    public javax.swing.JTextField portField;
    private javax.swing.JLabel portLabel;
    public javax.swing.JTextField selectedUserDiffieHellmanYField;
    private javax.swing.JLabel selectedUserDiffieHellmanYLabel;
    public javax.swing.JButton sendButton;
    private javax.swing.JLabel spacerLabel;
    public javax.swing.JCheckBox startCheck;
    private javax.swing.JLabel startLabel;
    public javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    public javax.swing.JButton viewDiffieHellmanButton;
    // End of variables declaration//GEN-END:variables
}
