/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.socketchat.ui;

/**
 *
 * @author User
 */
public class MyFrame3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MyFrame3.class.getName());

    /**
     * Creates new form MyFrame3
     */
    public MyFrame3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        headerPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        controlsPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        portLabel = new javax.swing.JLabel();
        startLabel = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        startCheck = new javax.swing.JCheckBox();
        spacerLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        addressHeaderPanel = new javax.swing.JPanel();
        addressesLabel = new javax.swing.JLabel();
        addAddressLabel = new javax.swing.JLabel();
        addressScrollPane = new javax.swing.JScrollPane();
        addressList = new javax.swing.JList<>();
        messagePanel = new javax.swing.JPanel();
        messageHeaderPanel = new javax.swing.JPanel();
        messagesLabel = new javax.swing.JLabel();
        clearLabel = new javax.swing.JLabel();
        messageScrollPane = new javax.swing.JScrollPane();
        messages = new javax.swing.JTextArea();
        messageInputPanel = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UDP Broadcast Chat");
        setMinimumSize(new java.awt.Dimension(920, 560));
        setPreferredSize(new java.awt.Dimension(1200, 760));

        headerPanel.setLayout(new java.awt.BorderLayout());

        titleLabel.setText("(o) UDP BROADCAST");
        titleLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 14, 7, 14));
        headerPanel.add(titleLabel, java.awt.BorderLayout.NORTH);

        controlsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 14, 10, 14));
        controlsPanel.setLayout(new java.awt.GridBagLayout());

        addressLabel.setText("BROADCAST IP ADDRESS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(addressLabel, gridBagConstraints);

        portLabel.setText("UDP PORT");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(portLabel, gridBagConstraints);

        startLabel.setText("START");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 14);
        controlsPanel.add(startLabel, gridBagConstraints);

        addressField.setPreferredSize(new java.awt.Dimension(150, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(addressField, gridBagConstraints);

        portField.setText("9000");
        portField.setPreferredSize(new java.awt.Dimension(82, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(portField, gridBagConstraints);

        startCheck.setSelected(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 14);
        controlsPanel.add(startCheck, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        controlsPanel.add(spacerLabel, gridBagConstraints);

        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statusLabel.setText("* LISTENING");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        controlsPanel.add(statusLabel, gridBagConstraints);

        headerPanel.add(controlsPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        centerPanel.setLayout(new java.awt.BorderLayout());

        addressPanel.setPreferredSize(new java.awt.Dimension(184, 10));
        addressPanel.setLayout(new java.awt.BorderLayout());

        addressHeaderPanel.setLayout(new java.awt.BorderLayout());

        addressesLabel.setText("ADDRESSES");
        addressesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        addressHeaderPanel.add(addressesLabel, java.awt.BorderLayout.WEST);

        addAddressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addAddressLabel.setText("+");
        addAddressLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        addressHeaderPanel.add(addAddressLabel, java.awt.BorderLayout.EAST);

        addressPanel.add(addressHeaderPanel, java.awt.BorderLayout.NORTH);

        addressList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        addressList.setFixedCellHeight(26);
        addressScrollPane.setViewportView(addressList);

        addressPanel.add(addressScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(addressPanel, java.awt.BorderLayout.WEST);

        messagePanel.setLayout(new java.awt.BorderLayout());

        messageHeaderPanel.setLayout(new java.awt.BorderLayout());

        messagesLabel.setText("MESSAGES");
        messagesLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageHeaderPanel.add(messagesLabel, java.awt.BorderLayout.WEST);

        clearLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        clearLabel.setText("CLEAR");
        clearLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageHeaderPanel.add(clearLabel, java.awt.BorderLayout.EAST);

        messagePanel.add(messageHeaderPanel, java.awt.BorderLayout.NORTH);

        messages.setEditable(false);
        messages.setColumns(20);
        messages.setLineWrap(true);
        messages.setRows(5);
        messages.setWrapStyleWord(true);
        messages.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        messageScrollPane.setViewportView(messages);

        messagePanel.add(messageScrollPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(messagePanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        messageInputPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12));
        messageInputPanel.setLayout(new java.awt.BorderLayout(8, 0));
        messageInputPanel.add(inputField, java.awt.BorderLayout.CENTER);

        sendButton.setText("Send");
        messageInputPanel.add(sendButton, java.awt.BorderLayout.EAST);

        getContentPane().add(messageInputPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MyFrame3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addAddressLabel;
    private javax.swing.JTextField addressField;
    private javax.swing.JPanel addressHeaderPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JList<String> addressList;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JScrollPane addressScrollPane;
    private javax.swing.JLabel addressesLabel;
    private javax.swing.JPanel centerPanel;
    private javax.swing.JLabel clearLabel;
    private javax.swing.JPanel controlsPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JTextField inputField;
    private javax.swing.JPanel messageHeaderPanel;
    private javax.swing.JPanel messageInputPanel;
    private javax.swing.JPanel messagePanel;
    private javax.swing.JScrollPane messageScrollPane;
    private javax.swing.JTextArea messages;
    private javax.swing.JLabel messagesLabel;
    private javax.swing.JTextField portField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel spacerLabel;
    private javax.swing.JCheckBox startCheck;
    private javax.swing.JLabel startLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
